/*
 * generated by Xtext
 */
package mondo.collab.security.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SecurityAccessRuntimeModule extends mondo.collab.security.xtext.AbstractSecurityAccessRuntimeModule {

}
