Document: mondocollab
Title: Debian mondocollab Manual
Author: Csaba Debreceni
Abstract: This manual describes what mondocollab is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mondocollab/mondocollab.sgml.gz

Format: postscript
Files: /usr/share/doc/mondocollab/mondocollab.ps.gz

Format: text
Files: /usr/share/doc/mondocollab/mondocollab.text.gz

Format: HTML
Index: /usr/share/doc/mondocollab/html/index.html
Files: /usr/share/doc/mondocollab/html/*.html
