/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCErrorReaction;
import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit48}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit48Validator {
	boolean validate();

	boolean validateInput__iTemp1(WTCInput value);
	boolean validateInput__iTemp2(WTCInput value);
	boolean validateInput__iTemp3(WTCInput value);
	boolean validateOutput__oFan(WTCOutput value);
	boolean validateParameter__pTempLimit1(WTCParam value);
	boolean validateParameter__pTempLimit2(WTCParam value);
	boolean validateParameter__pTempLimit3(WTCParam value);
	boolean validateFault__fFault1(WTCFault value);
	boolean validateErrorReaction__erReaction1(WTCErrorReaction value);
	boolean validateErrorReaction__erReaction2(WTCErrorReaction value);
}
