/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit96}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit96Validator {
	boolean validate();

	boolean validateInput__iHMIDisableOrder(WTCInput value);
	boolean validateInput__iElementStatus(WTCInput value);
	boolean validateOutput__oElementRol(WTCOutput value);
	boolean validateParameter__pMaxElements(WTCParam value);
}
