/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit132}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit132Validator {
	boolean validate();

	boolean validateInput__iTeeth1(WTCInput value);
	boolean validateInput__iTeeth2(WTCInput value);
	boolean validateInput__iTwistAngle(WTCInput value);
	boolean validateOutput__oTwistAngle(WTCOutput value);
	boolean validateParameter__pDegreesPerPulse(WTCParam value);
}
