/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCErrorReaction;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit86}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit86Validator {
	boolean validate();

	boolean validateInput__iPitchHwStandby(WTCInput value);
	boolean validateInput__iPitchHwFault(WTCInput value);
	boolean validateInput__iPitchStopCommand(WTCInput value);
	boolean validateInput__iPitchBrakePosition(WTCInput value);
	boolean validateOutput__oBrakes(WTCOutput value);
	boolean validateOutput__oPitchNormalOrder(WTCOutput value);
	boolean validateOutput__oPitchEmergencyOrder(WTCOutput value);
	boolean validateOutput__oPitchTestUCapOrder(WTCOutput value);
	boolean validateErrorReaction__erEmergency(WTCErrorReaction value);
	boolean validateErrorReaction__erSecurityLine(WTCErrorReaction value);
}
