/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit20}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit20Validator {
	boolean validate();

	boolean validateInput__iMasterOrder(WTCInput value);
	boolean validateInput__iInverterOrder(WTCInput value);
	boolean validateInput__iChangeOrder(WTCInput value);
	boolean validateInput__iManualStop(WTCInput value);
	boolean validateOutput__oMasterSelected(WTCOutput value);
	boolean validateOutput__oInverterEnabled(WTCOutput value);
	boolean validateOutput__oForceInvOff(WTCOutput value);
}
