/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCErrorReaction;
import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit61}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit61Validator {
	boolean validate();

	boolean validateInput__iInverterToOnOrder(WTCInput value);
	boolean validateInput__iInverterReadyRef(WTCInput value);
	boolean validateInput__iRemoteResetOrder(WTCInput value);
	boolean validateInput__iInverterTorqueReg(WTCInput value);
	boolean validateInput__iInverterHwState(WTCInput value);
	boolean validateInput__iResetOrder(WTCInput value);
	boolean validateInput__iMotorizing(WTCInput value);
	boolean validateOutput__oInverterToOn(WTCOutput value);
	boolean validateOutput__oInverterResetCommand(WTCOutput value);
	boolean validateOutput__oInverterTorqueRef(WTCOutput value);
	boolean validateOutput__oInverterResetAlarms(WTCOutput value);
	boolean validateFault__fEtherCAT(WTCFault value);
	boolean validateTimer__tResetTime(WTCTimer value);
	boolean validateTimer__tDelayBetweenResets(WTCTimer value);
	boolean validateErrorReaction__erStop(WTCErrorReaction value);
}
