/**
 */
package WTSpec.provider;

import WTSpec.util.WTSpecAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class WTSpecItemProviderAdapterFactory extends WTSpecAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public WTSpecItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.WT} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WTItemProvider wtItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.WT}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWTAdapter() {
		if (wtItemProvider == null) {
			wtItemProvider = new WTItemProvider(this);
		}

		return wtItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.SystemInput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemInputItemProvider systemInputItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.SystemInput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemInputAdapter() {
		if (systemInputItemProvider == null) {
			systemInputItemProvider = new SystemInputItemProvider(this);
		}

		return systemInputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.SystemOutput} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemOutputItemProvider systemOutputItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.SystemOutput}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemOutputAdapter() {
		if (systemOutputItemProvider == null) {
			systemOutputItemProvider = new SystemOutputItemProvider(this);
		}

		return systemOutputItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.SystemFault} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemFaultItemProvider systemFaultItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.SystemFault}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemFaultAdapter() {
		if (systemFaultItemProvider == null) {
			systemFaultItemProvider = new SystemFaultItemProvider(this);
		}

		return systemFaultItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.SystemParam} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemParamItemProvider systemParamItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.SystemParam}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemParamAdapter() {
		if (systemParamItemProvider == null) {
			systemParamItemProvider = new SystemParamItemProvider(this);
		}

		return systemParamItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.SystemTimer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemTimerItemProvider systemTimerItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.SystemTimer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemTimerAdapter() {
		if (systemTimerItemProvider == null) {
			systemTimerItemProvider = new SystemTimerItemProvider(this);
		}

		return systemTimerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.SystemVariable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemVariableItemProvider systemVariableItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.SystemVariable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemVariableAdapter() {
		if (systemVariableItemProvider == null) {
			systemVariableItemProvider = new SystemVariableItemProvider(this);
		}

		return systemVariableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.SystemErrorReaction} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SystemErrorReactionItemProvider systemErrorReactionItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.SystemErrorReaction}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSystemErrorReactionAdapter() {
		if (systemErrorReactionItemProvider == null) {
			systemErrorReactionItemProvider = new SystemErrorReactionItemProvider(this);
		}

		return systemErrorReactionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.Subsystem} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubsystemItemProvider subsystemItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.Subsystem}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubsystemAdapter() {
		if (subsystemItemProvider == null) {
			subsystemItemProvider = new SubsystemItemProvider(this);
		}

		return subsystemItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit1} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit1ItemProvider ctrlUnit1ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit1}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit1Adapter() {
		if (ctrlUnit1ItemProvider == null) {
			ctrlUnit1ItemProvider = new CtrlUnit1ItemProvider(this);
		}

		return ctrlUnit1ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit2} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit2ItemProvider ctrlUnit2ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit2}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit2Adapter() {
		if (ctrlUnit2ItemProvider == null) {
			ctrlUnit2ItemProvider = new CtrlUnit2ItemProvider(this);
		}

		return ctrlUnit2ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit3} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit3ItemProvider ctrlUnit3ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit3}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit3Adapter() {
		if (ctrlUnit3ItemProvider == null) {
			ctrlUnit3ItemProvider = new CtrlUnit3ItemProvider(this);
		}

		return ctrlUnit3ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit4} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit4ItemProvider ctrlUnit4ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit4}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit4Adapter() {
		if (ctrlUnit4ItemProvider == null) {
			ctrlUnit4ItemProvider = new CtrlUnit4ItemProvider(this);
		}

		return ctrlUnit4ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit5} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit5ItemProvider ctrlUnit5ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit5}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit5Adapter() {
		if (ctrlUnit5ItemProvider == null) {
			ctrlUnit5ItemProvider = new CtrlUnit5ItemProvider(this);
		}

		return ctrlUnit5ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit6} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit6ItemProvider ctrlUnit6ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit6}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit6Adapter() {
		if (ctrlUnit6ItemProvider == null) {
			ctrlUnit6ItemProvider = new CtrlUnit6ItemProvider(this);
		}

		return ctrlUnit6ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit7} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit7ItemProvider ctrlUnit7ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit7}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit7Adapter() {
		if (ctrlUnit7ItemProvider == null) {
			ctrlUnit7ItemProvider = new CtrlUnit7ItemProvider(this);
		}

		return ctrlUnit7ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit8} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit8ItemProvider ctrlUnit8ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit8}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit8Adapter() {
		if (ctrlUnit8ItemProvider == null) {
			ctrlUnit8ItemProvider = new CtrlUnit8ItemProvider(this);
		}

		return ctrlUnit8ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit9} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit9ItemProvider ctrlUnit9ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit9}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit9Adapter() {
		if (ctrlUnit9ItemProvider == null) {
			ctrlUnit9ItemProvider = new CtrlUnit9ItemProvider(this);
		}

		return ctrlUnit9ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit10} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit10ItemProvider ctrlUnit10ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit10}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit10Adapter() {
		if (ctrlUnit10ItemProvider == null) {
			ctrlUnit10ItemProvider = new CtrlUnit10ItemProvider(this);
		}

		return ctrlUnit10ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit11} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit11ItemProvider ctrlUnit11ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit11}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit11Adapter() {
		if (ctrlUnit11ItemProvider == null) {
			ctrlUnit11ItemProvider = new CtrlUnit11ItemProvider(this);
		}

		return ctrlUnit11ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit12} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit12ItemProvider ctrlUnit12ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit12}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit12Adapter() {
		if (ctrlUnit12ItemProvider == null) {
			ctrlUnit12ItemProvider = new CtrlUnit12ItemProvider(this);
		}

		return ctrlUnit12ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit13} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit13ItemProvider ctrlUnit13ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit13}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit13Adapter() {
		if (ctrlUnit13ItemProvider == null) {
			ctrlUnit13ItemProvider = new CtrlUnit13ItemProvider(this);
		}

		return ctrlUnit13ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit14} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit14ItemProvider ctrlUnit14ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit14}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit14Adapter() {
		if (ctrlUnit14ItemProvider == null) {
			ctrlUnit14ItemProvider = new CtrlUnit14ItemProvider(this);
		}

		return ctrlUnit14ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit15} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit15ItemProvider ctrlUnit15ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit15}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit15Adapter() {
		if (ctrlUnit15ItemProvider == null) {
			ctrlUnit15ItemProvider = new CtrlUnit15ItemProvider(this);
		}

		return ctrlUnit15ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit16} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit16ItemProvider ctrlUnit16ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit16}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit16Adapter() {
		if (ctrlUnit16ItemProvider == null) {
			ctrlUnit16ItemProvider = new CtrlUnit16ItemProvider(this);
		}

		return ctrlUnit16ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit17} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit17ItemProvider ctrlUnit17ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit17}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit17Adapter() {
		if (ctrlUnit17ItemProvider == null) {
			ctrlUnit17ItemProvider = new CtrlUnit17ItemProvider(this);
		}

		return ctrlUnit17ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit18} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit18ItemProvider ctrlUnit18ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit18}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit18Adapter() {
		if (ctrlUnit18ItemProvider == null) {
			ctrlUnit18ItemProvider = new CtrlUnit18ItemProvider(this);
		}

		return ctrlUnit18ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit19} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit19ItemProvider ctrlUnit19ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit19}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit19Adapter() {
		if (ctrlUnit19ItemProvider == null) {
			ctrlUnit19ItemProvider = new CtrlUnit19ItemProvider(this);
		}

		return ctrlUnit19ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit20} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit20ItemProvider ctrlUnit20ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit20}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit20Adapter() {
		if (ctrlUnit20ItemProvider == null) {
			ctrlUnit20ItemProvider = new CtrlUnit20ItemProvider(this);
		}

		return ctrlUnit20ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit21} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit21ItemProvider ctrlUnit21ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit21}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit21Adapter() {
		if (ctrlUnit21ItemProvider == null) {
			ctrlUnit21ItemProvider = new CtrlUnit21ItemProvider(this);
		}

		return ctrlUnit21ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit22} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit22ItemProvider ctrlUnit22ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit22}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit22Adapter() {
		if (ctrlUnit22ItemProvider == null) {
			ctrlUnit22ItemProvider = new CtrlUnit22ItemProvider(this);
		}

		return ctrlUnit22ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit23} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit23ItemProvider ctrlUnit23ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit23}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit23Adapter() {
		if (ctrlUnit23ItemProvider == null) {
			ctrlUnit23ItemProvider = new CtrlUnit23ItemProvider(this);
		}

		return ctrlUnit23ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit24} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit24ItemProvider ctrlUnit24ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit24}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit24Adapter() {
		if (ctrlUnit24ItemProvider == null) {
			ctrlUnit24ItemProvider = new CtrlUnit24ItemProvider(this);
		}

		return ctrlUnit24ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit25} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit25ItemProvider ctrlUnit25ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit25}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit25Adapter() {
		if (ctrlUnit25ItemProvider == null) {
			ctrlUnit25ItemProvider = new CtrlUnit25ItemProvider(this);
		}

		return ctrlUnit25ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit26} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit26ItemProvider ctrlUnit26ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit26}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit26Adapter() {
		if (ctrlUnit26ItemProvider == null) {
			ctrlUnit26ItemProvider = new CtrlUnit26ItemProvider(this);
		}

		return ctrlUnit26ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit27} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit27ItemProvider ctrlUnit27ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit27}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit27Adapter() {
		if (ctrlUnit27ItemProvider == null) {
			ctrlUnit27ItemProvider = new CtrlUnit27ItemProvider(this);
		}

		return ctrlUnit27ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit28} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit28ItemProvider ctrlUnit28ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit28}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit28Adapter() {
		if (ctrlUnit28ItemProvider == null) {
			ctrlUnit28ItemProvider = new CtrlUnit28ItemProvider(this);
		}

		return ctrlUnit28ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit29} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit29ItemProvider ctrlUnit29ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit29}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit29Adapter() {
		if (ctrlUnit29ItemProvider == null) {
			ctrlUnit29ItemProvider = new CtrlUnit29ItemProvider(this);
		}

		return ctrlUnit29ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit30} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit30ItemProvider ctrlUnit30ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit30}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit30Adapter() {
		if (ctrlUnit30ItemProvider == null) {
			ctrlUnit30ItemProvider = new CtrlUnit30ItemProvider(this);
		}

		return ctrlUnit30ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit31} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit31ItemProvider ctrlUnit31ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit31}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit31Adapter() {
		if (ctrlUnit31ItemProvider == null) {
			ctrlUnit31ItemProvider = new CtrlUnit31ItemProvider(this);
		}

		return ctrlUnit31ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit32} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit32ItemProvider ctrlUnit32ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit32}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit32Adapter() {
		if (ctrlUnit32ItemProvider == null) {
			ctrlUnit32ItemProvider = new CtrlUnit32ItemProvider(this);
		}

		return ctrlUnit32ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit33} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit33ItemProvider ctrlUnit33ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit33}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit33Adapter() {
		if (ctrlUnit33ItemProvider == null) {
			ctrlUnit33ItemProvider = new CtrlUnit33ItemProvider(this);
		}

		return ctrlUnit33ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit34} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit34ItemProvider ctrlUnit34ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit34}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit34Adapter() {
		if (ctrlUnit34ItemProvider == null) {
			ctrlUnit34ItemProvider = new CtrlUnit34ItemProvider(this);
		}

		return ctrlUnit34ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit35} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit35ItemProvider ctrlUnit35ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit35}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit35Adapter() {
		if (ctrlUnit35ItemProvider == null) {
			ctrlUnit35ItemProvider = new CtrlUnit35ItemProvider(this);
		}

		return ctrlUnit35ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit36} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit36ItemProvider ctrlUnit36ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit36}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit36Adapter() {
		if (ctrlUnit36ItemProvider == null) {
			ctrlUnit36ItemProvider = new CtrlUnit36ItemProvider(this);
		}

		return ctrlUnit36ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit37} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit37ItemProvider ctrlUnit37ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit37}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit37Adapter() {
		if (ctrlUnit37ItemProvider == null) {
			ctrlUnit37ItemProvider = new CtrlUnit37ItemProvider(this);
		}

		return ctrlUnit37ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit38} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit38ItemProvider ctrlUnit38ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit38}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit38Adapter() {
		if (ctrlUnit38ItemProvider == null) {
			ctrlUnit38ItemProvider = new CtrlUnit38ItemProvider(this);
		}

		return ctrlUnit38ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit39} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit39ItemProvider ctrlUnit39ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit39}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit39Adapter() {
		if (ctrlUnit39ItemProvider == null) {
			ctrlUnit39ItemProvider = new CtrlUnit39ItemProvider(this);
		}

		return ctrlUnit39ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit40} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit40ItemProvider ctrlUnit40ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit40}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit40Adapter() {
		if (ctrlUnit40ItemProvider == null) {
			ctrlUnit40ItemProvider = new CtrlUnit40ItemProvider(this);
		}

		return ctrlUnit40ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit41} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit41ItemProvider ctrlUnit41ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit41}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit41Adapter() {
		if (ctrlUnit41ItemProvider == null) {
			ctrlUnit41ItemProvider = new CtrlUnit41ItemProvider(this);
		}

		return ctrlUnit41ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit42} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit42ItemProvider ctrlUnit42ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit42}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit42Adapter() {
		if (ctrlUnit42ItemProvider == null) {
			ctrlUnit42ItemProvider = new CtrlUnit42ItemProvider(this);
		}

		return ctrlUnit42ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit43} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit43ItemProvider ctrlUnit43ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit43}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit43Adapter() {
		if (ctrlUnit43ItemProvider == null) {
			ctrlUnit43ItemProvider = new CtrlUnit43ItemProvider(this);
		}

		return ctrlUnit43ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit44} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit44ItemProvider ctrlUnit44ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit44}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit44Adapter() {
		if (ctrlUnit44ItemProvider == null) {
			ctrlUnit44ItemProvider = new CtrlUnit44ItemProvider(this);
		}

		return ctrlUnit44ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit45} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit45ItemProvider ctrlUnit45ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit45}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit45Adapter() {
		if (ctrlUnit45ItemProvider == null) {
			ctrlUnit45ItemProvider = new CtrlUnit45ItemProvider(this);
		}

		return ctrlUnit45ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit46} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit46ItemProvider ctrlUnit46ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit46}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit46Adapter() {
		if (ctrlUnit46ItemProvider == null) {
			ctrlUnit46ItemProvider = new CtrlUnit46ItemProvider(this);
		}

		return ctrlUnit46ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit47} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit47ItemProvider ctrlUnit47ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit47}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit47Adapter() {
		if (ctrlUnit47ItemProvider == null) {
			ctrlUnit47ItemProvider = new CtrlUnit47ItemProvider(this);
		}

		return ctrlUnit47ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit48} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit48ItemProvider ctrlUnit48ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit48}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit48Adapter() {
		if (ctrlUnit48ItemProvider == null) {
			ctrlUnit48ItemProvider = new CtrlUnit48ItemProvider(this);
		}

		return ctrlUnit48ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit49} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit49ItemProvider ctrlUnit49ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit49}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit49Adapter() {
		if (ctrlUnit49ItemProvider == null) {
			ctrlUnit49ItemProvider = new CtrlUnit49ItemProvider(this);
		}

		return ctrlUnit49ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit50} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit50ItemProvider ctrlUnit50ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit50}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit50Adapter() {
		if (ctrlUnit50ItemProvider == null) {
			ctrlUnit50ItemProvider = new CtrlUnit50ItemProvider(this);
		}

		return ctrlUnit50ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit51} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit51ItemProvider ctrlUnit51ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit51}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit51Adapter() {
		if (ctrlUnit51ItemProvider == null) {
			ctrlUnit51ItemProvider = new CtrlUnit51ItemProvider(this);
		}

		return ctrlUnit51ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit52} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit52ItemProvider ctrlUnit52ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit52}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit52Adapter() {
		if (ctrlUnit52ItemProvider == null) {
			ctrlUnit52ItemProvider = new CtrlUnit52ItemProvider(this);
		}

		return ctrlUnit52ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit53} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit53ItemProvider ctrlUnit53ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit53}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit53Adapter() {
		if (ctrlUnit53ItemProvider == null) {
			ctrlUnit53ItemProvider = new CtrlUnit53ItemProvider(this);
		}

		return ctrlUnit53ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit54} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit54ItemProvider ctrlUnit54ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit54}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit54Adapter() {
		if (ctrlUnit54ItemProvider == null) {
			ctrlUnit54ItemProvider = new CtrlUnit54ItemProvider(this);
		}

		return ctrlUnit54ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit55} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit55ItemProvider ctrlUnit55ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit55}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit55Adapter() {
		if (ctrlUnit55ItemProvider == null) {
			ctrlUnit55ItemProvider = new CtrlUnit55ItemProvider(this);
		}

		return ctrlUnit55ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit56} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit56ItemProvider ctrlUnit56ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit56}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit56Adapter() {
		if (ctrlUnit56ItemProvider == null) {
			ctrlUnit56ItemProvider = new CtrlUnit56ItemProvider(this);
		}

		return ctrlUnit56ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit57} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit57ItemProvider ctrlUnit57ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit57}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit57Adapter() {
		if (ctrlUnit57ItemProvider == null) {
			ctrlUnit57ItemProvider = new CtrlUnit57ItemProvider(this);
		}

		return ctrlUnit57ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit58} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit58ItemProvider ctrlUnit58ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit58}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit58Adapter() {
		if (ctrlUnit58ItemProvider == null) {
			ctrlUnit58ItemProvider = new CtrlUnit58ItemProvider(this);
		}

		return ctrlUnit58ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit59} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit59ItemProvider ctrlUnit59ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit59}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit59Adapter() {
		if (ctrlUnit59ItemProvider == null) {
			ctrlUnit59ItemProvider = new CtrlUnit59ItemProvider(this);
		}

		return ctrlUnit59ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit60} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit60ItemProvider ctrlUnit60ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit60}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit60Adapter() {
		if (ctrlUnit60ItemProvider == null) {
			ctrlUnit60ItemProvider = new CtrlUnit60ItemProvider(this);
		}

		return ctrlUnit60ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit61} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit61ItemProvider ctrlUnit61ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit61}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit61Adapter() {
		if (ctrlUnit61ItemProvider == null) {
			ctrlUnit61ItemProvider = new CtrlUnit61ItemProvider(this);
		}

		return ctrlUnit61ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit62} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit62ItemProvider ctrlUnit62ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit62}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit62Adapter() {
		if (ctrlUnit62ItemProvider == null) {
			ctrlUnit62ItemProvider = new CtrlUnit62ItemProvider(this);
		}

		return ctrlUnit62ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit63} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit63ItemProvider ctrlUnit63ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit63}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit63Adapter() {
		if (ctrlUnit63ItemProvider == null) {
			ctrlUnit63ItemProvider = new CtrlUnit63ItemProvider(this);
		}

		return ctrlUnit63ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit64} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit64ItemProvider ctrlUnit64ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit64}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit64Adapter() {
		if (ctrlUnit64ItemProvider == null) {
			ctrlUnit64ItemProvider = new CtrlUnit64ItemProvider(this);
		}

		return ctrlUnit64ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit65} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit65ItemProvider ctrlUnit65ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit65}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit65Adapter() {
		if (ctrlUnit65ItemProvider == null) {
			ctrlUnit65ItemProvider = new CtrlUnit65ItemProvider(this);
		}

		return ctrlUnit65ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit66} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit66ItemProvider ctrlUnit66ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit66}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit66Adapter() {
		if (ctrlUnit66ItemProvider == null) {
			ctrlUnit66ItemProvider = new CtrlUnit66ItemProvider(this);
		}

		return ctrlUnit66ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit67} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit67ItemProvider ctrlUnit67ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit67}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit67Adapter() {
		if (ctrlUnit67ItemProvider == null) {
			ctrlUnit67ItemProvider = new CtrlUnit67ItemProvider(this);
		}

		return ctrlUnit67ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit68} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit68ItemProvider ctrlUnit68ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit68}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit68Adapter() {
		if (ctrlUnit68ItemProvider == null) {
			ctrlUnit68ItemProvider = new CtrlUnit68ItemProvider(this);
		}

		return ctrlUnit68ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit69} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit69ItemProvider ctrlUnit69ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit69}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit69Adapter() {
		if (ctrlUnit69ItemProvider == null) {
			ctrlUnit69ItemProvider = new CtrlUnit69ItemProvider(this);
		}

		return ctrlUnit69ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit70} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit70ItemProvider ctrlUnit70ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit70}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit70Adapter() {
		if (ctrlUnit70ItemProvider == null) {
			ctrlUnit70ItemProvider = new CtrlUnit70ItemProvider(this);
		}

		return ctrlUnit70ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit71} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit71ItemProvider ctrlUnit71ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit71}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit71Adapter() {
		if (ctrlUnit71ItemProvider == null) {
			ctrlUnit71ItemProvider = new CtrlUnit71ItemProvider(this);
		}

		return ctrlUnit71ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit72} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit72ItemProvider ctrlUnit72ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit72}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit72Adapter() {
		if (ctrlUnit72ItemProvider == null) {
			ctrlUnit72ItemProvider = new CtrlUnit72ItemProvider(this);
		}

		return ctrlUnit72ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit73} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit73ItemProvider ctrlUnit73ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit73}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit73Adapter() {
		if (ctrlUnit73ItemProvider == null) {
			ctrlUnit73ItemProvider = new CtrlUnit73ItemProvider(this);
		}

		return ctrlUnit73ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit74} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit74ItemProvider ctrlUnit74ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit74}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit74Adapter() {
		if (ctrlUnit74ItemProvider == null) {
			ctrlUnit74ItemProvider = new CtrlUnit74ItemProvider(this);
		}

		return ctrlUnit74ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit75} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit75ItemProvider ctrlUnit75ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit75}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit75Adapter() {
		if (ctrlUnit75ItemProvider == null) {
			ctrlUnit75ItemProvider = new CtrlUnit75ItemProvider(this);
		}

		return ctrlUnit75ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit76} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit76ItemProvider ctrlUnit76ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit76}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit76Adapter() {
		if (ctrlUnit76ItemProvider == null) {
			ctrlUnit76ItemProvider = new CtrlUnit76ItemProvider(this);
		}

		return ctrlUnit76ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit77} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit77ItemProvider ctrlUnit77ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit77}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit77Adapter() {
		if (ctrlUnit77ItemProvider == null) {
			ctrlUnit77ItemProvider = new CtrlUnit77ItemProvider(this);
		}

		return ctrlUnit77ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit78} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit78ItemProvider ctrlUnit78ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit78}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit78Adapter() {
		if (ctrlUnit78ItemProvider == null) {
			ctrlUnit78ItemProvider = new CtrlUnit78ItemProvider(this);
		}

		return ctrlUnit78ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit79} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit79ItemProvider ctrlUnit79ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit79}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit79Adapter() {
		if (ctrlUnit79ItemProvider == null) {
			ctrlUnit79ItemProvider = new CtrlUnit79ItemProvider(this);
		}

		return ctrlUnit79ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit80} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit80ItemProvider ctrlUnit80ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit80}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit80Adapter() {
		if (ctrlUnit80ItemProvider == null) {
			ctrlUnit80ItemProvider = new CtrlUnit80ItemProvider(this);
		}

		return ctrlUnit80ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit81} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit81ItemProvider ctrlUnit81ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit81}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit81Adapter() {
		if (ctrlUnit81ItemProvider == null) {
			ctrlUnit81ItemProvider = new CtrlUnit81ItemProvider(this);
		}

		return ctrlUnit81ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit82} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit82ItemProvider ctrlUnit82ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit82}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit82Adapter() {
		if (ctrlUnit82ItemProvider == null) {
			ctrlUnit82ItemProvider = new CtrlUnit82ItemProvider(this);
		}

		return ctrlUnit82ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit83} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit83ItemProvider ctrlUnit83ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit83}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit83Adapter() {
		if (ctrlUnit83ItemProvider == null) {
			ctrlUnit83ItemProvider = new CtrlUnit83ItemProvider(this);
		}

		return ctrlUnit83ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit84} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit84ItemProvider ctrlUnit84ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit84}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit84Adapter() {
		if (ctrlUnit84ItemProvider == null) {
			ctrlUnit84ItemProvider = new CtrlUnit84ItemProvider(this);
		}

		return ctrlUnit84ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit85} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit85ItemProvider ctrlUnit85ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit85}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit85Adapter() {
		if (ctrlUnit85ItemProvider == null) {
			ctrlUnit85ItemProvider = new CtrlUnit85ItemProvider(this);
		}

		return ctrlUnit85ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit86} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit86ItemProvider ctrlUnit86ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit86}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit86Adapter() {
		if (ctrlUnit86ItemProvider == null) {
			ctrlUnit86ItemProvider = new CtrlUnit86ItemProvider(this);
		}

		return ctrlUnit86ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit87} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit87ItemProvider ctrlUnit87ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit87}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit87Adapter() {
		if (ctrlUnit87ItemProvider == null) {
			ctrlUnit87ItemProvider = new CtrlUnit87ItemProvider(this);
		}

		return ctrlUnit87ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit88} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit88ItemProvider ctrlUnit88ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit88}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit88Adapter() {
		if (ctrlUnit88ItemProvider == null) {
			ctrlUnit88ItemProvider = new CtrlUnit88ItemProvider(this);
		}

		return ctrlUnit88ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit89} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit89ItemProvider ctrlUnit89ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit89}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit89Adapter() {
		if (ctrlUnit89ItemProvider == null) {
			ctrlUnit89ItemProvider = new CtrlUnit89ItemProvider(this);
		}

		return ctrlUnit89ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit90} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit90ItemProvider ctrlUnit90ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit90}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit90Adapter() {
		if (ctrlUnit90ItemProvider == null) {
			ctrlUnit90ItemProvider = new CtrlUnit90ItemProvider(this);
		}

		return ctrlUnit90ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit91} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit91ItemProvider ctrlUnit91ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit91}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit91Adapter() {
		if (ctrlUnit91ItemProvider == null) {
			ctrlUnit91ItemProvider = new CtrlUnit91ItemProvider(this);
		}

		return ctrlUnit91ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit92} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit92ItemProvider ctrlUnit92ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit92}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit92Adapter() {
		if (ctrlUnit92ItemProvider == null) {
			ctrlUnit92ItemProvider = new CtrlUnit92ItemProvider(this);
		}

		return ctrlUnit92ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit93} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit93ItemProvider ctrlUnit93ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit93}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit93Adapter() {
		if (ctrlUnit93ItemProvider == null) {
			ctrlUnit93ItemProvider = new CtrlUnit93ItemProvider(this);
		}

		return ctrlUnit93ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit94} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit94ItemProvider ctrlUnit94ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit94}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit94Adapter() {
		if (ctrlUnit94ItemProvider == null) {
			ctrlUnit94ItemProvider = new CtrlUnit94ItemProvider(this);
		}

		return ctrlUnit94ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit95} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit95ItemProvider ctrlUnit95ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit95}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit95Adapter() {
		if (ctrlUnit95ItemProvider == null) {
			ctrlUnit95ItemProvider = new CtrlUnit95ItemProvider(this);
		}

		return ctrlUnit95ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit96} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit96ItemProvider ctrlUnit96ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit96}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit96Adapter() {
		if (ctrlUnit96ItemProvider == null) {
			ctrlUnit96ItemProvider = new CtrlUnit96ItemProvider(this);
		}

		return ctrlUnit96ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit97} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit97ItemProvider ctrlUnit97ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit97}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit97Adapter() {
		if (ctrlUnit97ItemProvider == null) {
			ctrlUnit97ItemProvider = new CtrlUnit97ItemProvider(this);
		}

		return ctrlUnit97ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit98} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit98ItemProvider ctrlUnit98ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit98}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit98Adapter() {
		if (ctrlUnit98ItemProvider == null) {
			ctrlUnit98ItemProvider = new CtrlUnit98ItemProvider(this);
		}

		return ctrlUnit98ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit99} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit99ItemProvider ctrlUnit99ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit99}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit99Adapter() {
		if (ctrlUnit99ItemProvider == null) {
			ctrlUnit99ItemProvider = new CtrlUnit99ItemProvider(this);
		}

		return ctrlUnit99ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit100} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit100ItemProvider ctrlUnit100ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit100}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit100Adapter() {
		if (ctrlUnit100ItemProvider == null) {
			ctrlUnit100ItemProvider = new CtrlUnit100ItemProvider(this);
		}

		return ctrlUnit100ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit101} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit101ItemProvider ctrlUnit101ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit101}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit101Adapter() {
		if (ctrlUnit101ItemProvider == null) {
			ctrlUnit101ItemProvider = new CtrlUnit101ItemProvider(this);
		}

		return ctrlUnit101ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit102} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit102ItemProvider ctrlUnit102ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit102}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit102Adapter() {
		if (ctrlUnit102ItemProvider == null) {
			ctrlUnit102ItemProvider = new CtrlUnit102ItemProvider(this);
		}

		return ctrlUnit102ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit103} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit103ItemProvider ctrlUnit103ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit103}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit103Adapter() {
		if (ctrlUnit103ItemProvider == null) {
			ctrlUnit103ItemProvider = new CtrlUnit103ItemProvider(this);
		}

		return ctrlUnit103ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit104} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit104ItemProvider ctrlUnit104ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit104}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit104Adapter() {
		if (ctrlUnit104ItemProvider == null) {
			ctrlUnit104ItemProvider = new CtrlUnit104ItemProvider(this);
		}

		return ctrlUnit104ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit105} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit105ItemProvider ctrlUnit105ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit105}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit105Adapter() {
		if (ctrlUnit105ItemProvider == null) {
			ctrlUnit105ItemProvider = new CtrlUnit105ItemProvider(this);
		}

		return ctrlUnit105ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit106} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit106ItemProvider ctrlUnit106ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit106}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit106Adapter() {
		if (ctrlUnit106ItemProvider == null) {
			ctrlUnit106ItemProvider = new CtrlUnit106ItemProvider(this);
		}

		return ctrlUnit106ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit107} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit107ItemProvider ctrlUnit107ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit107}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit107Adapter() {
		if (ctrlUnit107ItemProvider == null) {
			ctrlUnit107ItemProvider = new CtrlUnit107ItemProvider(this);
		}

		return ctrlUnit107ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit108} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit108ItemProvider ctrlUnit108ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit108}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit108Adapter() {
		if (ctrlUnit108ItemProvider == null) {
			ctrlUnit108ItemProvider = new CtrlUnit108ItemProvider(this);
		}

		return ctrlUnit108ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit109} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit109ItemProvider ctrlUnit109ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit109}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit109Adapter() {
		if (ctrlUnit109ItemProvider == null) {
			ctrlUnit109ItemProvider = new CtrlUnit109ItemProvider(this);
		}

		return ctrlUnit109ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit110} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit110ItemProvider ctrlUnit110ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit110}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit110Adapter() {
		if (ctrlUnit110ItemProvider == null) {
			ctrlUnit110ItemProvider = new CtrlUnit110ItemProvider(this);
		}

		return ctrlUnit110ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit111} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit111ItemProvider ctrlUnit111ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit111}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit111Adapter() {
		if (ctrlUnit111ItemProvider == null) {
			ctrlUnit111ItemProvider = new CtrlUnit111ItemProvider(this);
		}

		return ctrlUnit111ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit112} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit112ItemProvider ctrlUnit112ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit112}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit112Adapter() {
		if (ctrlUnit112ItemProvider == null) {
			ctrlUnit112ItemProvider = new CtrlUnit112ItemProvider(this);
		}

		return ctrlUnit112ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit113} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit113ItemProvider ctrlUnit113ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit113}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit113Adapter() {
		if (ctrlUnit113ItemProvider == null) {
			ctrlUnit113ItemProvider = new CtrlUnit113ItemProvider(this);
		}

		return ctrlUnit113ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit114} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit114ItemProvider ctrlUnit114ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit114}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit114Adapter() {
		if (ctrlUnit114ItemProvider == null) {
			ctrlUnit114ItemProvider = new CtrlUnit114ItemProvider(this);
		}

		return ctrlUnit114ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit115} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit115ItemProvider ctrlUnit115ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit115}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit115Adapter() {
		if (ctrlUnit115ItemProvider == null) {
			ctrlUnit115ItemProvider = new CtrlUnit115ItemProvider(this);
		}

		return ctrlUnit115ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit116} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit116ItemProvider ctrlUnit116ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit116}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit116Adapter() {
		if (ctrlUnit116ItemProvider == null) {
			ctrlUnit116ItemProvider = new CtrlUnit116ItemProvider(this);
		}

		return ctrlUnit116ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit117} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit117ItemProvider ctrlUnit117ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit117}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit117Adapter() {
		if (ctrlUnit117ItemProvider == null) {
			ctrlUnit117ItemProvider = new CtrlUnit117ItemProvider(this);
		}

		return ctrlUnit117ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit118} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit118ItemProvider ctrlUnit118ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit118}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit118Adapter() {
		if (ctrlUnit118ItemProvider == null) {
			ctrlUnit118ItemProvider = new CtrlUnit118ItemProvider(this);
		}

		return ctrlUnit118ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit119} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit119ItemProvider ctrlUnit119ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit119}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit119Adapter() {
		if (ctrlUnit119ItemProvider == null) {
			ctrlUnit119ItemProvider = new CtrlUnit119ItemProvider(this);
		}

		return ctrlUnit119ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit120} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit120ItemProvider ctrlUnit120ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit120}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit120Adapter() {
		if (ctrlUnit120ItemProvider == null) {
			ctrlUnit120ItemProvider = new CtrlUnit120ItemProvider(this);
		}

		return ctrlUnit120ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit121} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit121ItemProvider ctrlUnit121ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit121}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit121Adapter() {
		if (ctrlUnit121ItemProvider == null) {
			ctrlUnit121ItemProvider = new CtrlUnit121ItemProvider(this);
		}

		return ctrlUnit121ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit122} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit122ItemProvider ctrlUnit122ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit122}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit122Adapter() {
		if (ctrlUnit122ItemProvider == null) {
			ctrlUnit122ItemProvider = new CtrlUnit122ItemProvider(this);
		}

		return ctrlUnit122ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit123} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit123ItemProvider ctrlUnit123ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit123}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit123Adapter() {
		if (ctrlUnit123ItemProvider == null) {
			ctrlUnit123ItemProvider = new CtrlUnit123ItemProvider(this);
		}

		return ctrlUnit123ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit124} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit124ItemProvider ctrlUnit124ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit124}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit124Adapter() {
		if (ctrlUnit124ItemProvider == null) {
			ctrlUnit124ItemProvider = new CtrlUnit124ItemProvider(this);
		}

		return ctrlUnit124ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit125} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit125ItemProvider ctrlUnit125ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit125}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit125Adapter() {
		if (ctrlUnit125ItemProvider == null) {
			ctrlUnit125ItemProvider = new CtrlUnit125ItemProvider(this);
		}

		return ctrlUnit125ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit126} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit126ItemProvider ctrlUnit126ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit126}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit126Adapter() {
		if (ctrlUnit126ItemProvider == null) {
			ctrlUnit126ItemProvider = new CtrlUnit126ItemProvider(this);
		}

		return ctrlUnit126ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit127} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit127ItemProvider ctrlUnit127ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit127}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit127Adapter() {
		if (ctrlUnit127ItemProvider == null) {
			ctrlUnit127ItemProvider = new CtrlUnit127ItemProvider(this);
		}

		return ctrlUnit127ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit128} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit128ItemProvider ctrlUnit128ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit128}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit128Adapter() {
		if (ctrlUnit128ItemProvider == null) {
			ctrlUnit128ItemProvider = new CtrlUnit128ItemProvider(this);
		}

		return ctrlUnit128ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit129} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit129ItemProvider ctrlUnit129ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit129}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit129Adapter() {
		if (ctrlUnit129ItemProvider == null) {
			ctrlUnit129ItemProvider = new CtrlUnit129ItemProvider(this);
		}

		return ctrlUnit129ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit130} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit130ItemProvider ctrlUnit130ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit130}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit130Adapter() {
		if (ctrlUnit130ItemProvider == null) {
			ctrlUnit130ItemProvider = new CtrlUnit130ItemProvider(this);
		}

		return ctrlUnit130ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit131} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit131ItemProvider ctrlUnit131ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit131}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit131Adapter() {
		if (ctrlUnit131ItemProvider == null) {
			ctrlUnit131ItemProvider = new CtrlUnit131ItemProvider(this);
		}

		return ctrlUnit131ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit132} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit132ItemProvider ctrlUnit132ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit132}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit132Adapter() {
		if (ctrlUnit132ItemProvider == null) {
			ctrlUnit132ItemProvider = new CtrlUnit132ItemProvider(this);
		}

		return ctrlUnit132ItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link WTSpec.CtrlUnit133} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CtrlUnit133ItemProvider ctrlUnit133ItemProvider;

	/**
	 * This creates an adapter for a {@link WTSpec.CtrlUnit133}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCtrlUnit133Adapter() {
		if (ctrlUnit133ItemProvider == null) {
			ctrlUnit133ItemProvider = new CtrlUnit133ItemProvider(this);
		}

		return ctrlUnit133ItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (wtItemProvider != null) wtItemProvider.dispose();
		if (systemInputItemProvider != null) systemInputItemProvider.dispose();
		if (systemOutputItemProvider != null) systemOutputItemProvider.dispose();
		if (systemFaultItemProvider != null) systemFaultItemProvider.dispose();
		if (systemParamItemProvider != null) systemParamItemProvider.dispose();
		if (systemTimerItemProvider != null) systemTimerItemProvider.dispose();
		if (systemVariableItemProvider != null) systemVariableItemProvider.dispose();
		if (systemErrorReactionItemProvider != null) systemErrorReactionItemProvider.dispose();
		if (subsystemItemProvider != null) subsystemItemProvider.dispose();
		if (ctrlUnit1ItemProvider != null) ctrlUnit1ItemProvider.dispose();
		if (ctrlUnit2ItemProvider != null) ctrlUnit2ItemProvider.dispose();
		if (ctrlUnit3ItemProvider != null) ctrlUnit3ItemProvider.dispose();
		if (ctrlUnit4ItemProvider != null) ctrlUnit4ItemProvider.dispose();
		if (ctrlUnit5ItemProvider != null) ctrlUnit5ItemProvider.dispose();
		if (ctrlUnit6ItemProvider != null) ctrlUnit6ItemProvider.dispose();
		if (ctrlUnit7ItemProvider != null) ctrlUnit7ItemProvider.dispose();
		if (ctrlUnit8ItemProvider != null) ctrlUnit8ItemProvider.dispose();
		if (ctrlUnit9ItemProvider != null) ctrlUnit9ItemProvider.dispose();
		if (ctrlUnit10ItemProvider != null) ctrlUnit10ItemProvider.dispose();
		if (ctrlUnit11ItemProvider != null) ctrlUnit11ItemProvider.dispose();
		if (ctrlUnit12ItemProvider != null) ctrlUnit12ItemProvider.dispose();
		if (ctrlUnit13ItemProvider != null) ctrlUnit13ItemProvider.dispose();
		if (ctrlUnit14ItemProvider != null) ctrlUnit14ItemProvider.dispose();
		if (ctrlUnit15ItemProvider != null) ctrlUnit15ItemProvider.dispose();
		if (ctrlUnit16ItemProvider != null) ctrlUnit16ItemProvider.dispose();
		if (ctrlUnit17ItemProvider != null) ctrlUnit17ItemProvider.dispose();
		if (ctrlUnit18ItemProvider != null) ctrlUnit18ItemProvider.dispose();
		if (ctrlUnit19ItemProvider != null) ctrlUnit19ItemProvider.dispose();
		if (ctrlUnit20ItemProvider != null) ctrlUnit20ItemProvider.dispose();
		if (ctrlUnit21ItemProvider != null) ctrlUnit21ItemProvider.dispose();
		if (ctrlUnit22ItemProvider != null) ctrlUnit22ItemProvider.dispose();
		if (ctrlUnit23ItemProvider != null) ctrlUnit23ItemProvider.dispose();
		if (ctrlUnit24ItemProvider != null) ctrlUnit24ItemProvider.dispose();
		if (ctrlUnit25ItemProvider != null) ctrlUnit25ItemProvider.dispose();
		if (ctrlUnit26ItemProvider != null) ctrlUnit26ItemProvider.dispose();
		if (ctrlUnit27ItemProvider != null) ctrlUnit27ItemProvider.dispose();
		if (ctrlUnit28ItemProvider != null) ctrlUnit28ItemProvider.dispose();
		if (ctrlUnit29ItemProvider != null) ctrlUnit29ItemProvider.dispose();
		if (ctrlUnit30ItemProvider != null) ctrlUnit30ItemProvider.dispose();
		if (ctrlUnit31ItemProvider != null) ctrlUnit31ItemProvider.dispose();
		if (ctrlUnit32ItemProvider != null) ctrlUnit32ItemProvider.dispose();
		if (ctrlUnit33ItemProvider != null) ctrlUnit33ItemProvider.dispose();
		if (ctrlUnit34ItemProvider != null) ctrlUnit34ItemProvider.dispose();
		if (ctrlUnit35ItemProvider != null) ctrlUnit35ItemProvider.dispose();
		if (ctrlUnit36ItemProvider != null) ctrlUnit36ItemProvider.dispose();
		if (ctrlUnit37ItemProvider != null) ctrlUnit37ItemProvider.dispose();
		if (ctrlUnit38ItemProvider != null) ctrlUnit38ItemProvider.dispose();
		if (ctrlUnit39ItemProvider != null) ctrlUnit39ItemProvider.dispose();
		if (ctrlUnit40ItemProvider != null) ctrlUnit40ItemProvider.dispose();
		if (ctrlUnit41ItemProvider != null) ctrlUnit41ItemProvider.dispose();
		if (ctrlUnit42ItemProvider != null) ctrlUnit42ItemProvider.dispose();
		if (ctrlUnit43ItemProvider != null) ctrlUnit43ItemProvider.dispose();
		if (ctrlUnit44ItemProvider != null) ctrlUnit44ItemProvider.dispose();
		if (ctrlUnit45ItemProvider != null) ctrlUnit45ItemProvider.dispose();
		if (ctrlUnit46ItemProvider != null) ctrlUnit46ItemProvider.dispose();
		if (ctrlUnit47ItemProvider != null) ctrlUnit47ItemProvider.dispose();
		if (ctrlUnit48ItemProvider != null) ctrlUnit48ItemProvider.dispose();
		if (ctrlUnit49ItemProvider != null) ctrlUnit49ItemProvider.dispose();
		if (ctrlUnit50ItemProvider != null) ctrlUnit50ItemProvider.dispose();
		if (ctrlUnit51ItemProvider != null) ctrlUnit51ItemProvider.dispose();
		if (ctrlUnit52ItemProvider != null) ctrlUnit52ItemProvider.dispose();
		if (ctrlUnit53ItemProvider != null) ctrlUnit53ItemProvider.dispose();
		if (ctrlUnit54ItemProvider != null) ctrlUnit54ItemProvider.dispose();
		if (ctrlUnit55ItemProvider != null) ctrlUnit55ItemProvider.dispose();
		if (ctrlUnit56ItemProvider != null) ctrlUnit56ItemProvider.dispose();
		if (ctrlUnit57ItemProvider != null) ctrlUnit57ItemProvider.dispose();
		if (ctrlUnit58ItemProvider != null) ctrlUnit58ItemProvider.dispose();
		if (ctrlUnit59ItemProvider != null) ctrlUnit59ItemProvider.dispose();
		if (ctrlUnit60ItemProvider != null) ctrlUnit60ItemProvider.dispose();
		if (ctrlUnit61ItemProvider != null) ctrlUnit61ItemProvider.dispose();
		if (ctrlUnit62ItemProvider != null) ctrlUnit62ItemProvider.dispose();
		if (ctrlUnit63ItemProvider != null) ctrlUnit63ItemProvider.dispose();
		if (ctrlUnit64ItemProvider != null) ctrlUnit64ItemProvider.dispose();
		if (ctrlUnit65ItemProvider != null) ctrlUnit65ItemProvider.dispose();
		if (ctrlUnit66ItemProvider != null) ctrlUnit66ItemProvider.dispose();
		if (ctrlUnit67ItemProvider != null) ctrlUnit67ItemProvider.dispose();
		if (ctrlUnit68ItemProvider != null) ctrlUnit68ItemProvider.dispose();
		if (ctrlUnit69ItemProvider != null) ctrlUnit69ItemProvider.dispose();
		if (ctrlUnit70ItemProvider != null) ctrlUnit70ItemProvider.dispose();
		if (ctrlUnit71ItemProvider != null) ctrlUnit71ItemProvider.dispose();
		if (ctrlUnit72ItemProvider != null) ctrlUnit72ItemProvider.dispose();
		if (ctrlUnit73ItemProvider != null) ctrlUnit73ItemProvider.dispose();
		if (ctrlUnit74ItemProvider != null) ctrlUnit74ItemProvider.dispose();
		if (ctrlUnit75ItemProvider != null) ctrlUnit75ItemProvider.dispose();
		if (ctrlUnit76ItemProvider != null) ctrlUnit76ItemProvider.dispose();
		if (ctrlUnit77ItemProvider != null) ctrlUnit77ItemProvider.dispose();
		if (ctrlUnit78ItemProvider != null) ctrlUnit78ItemProvider.dispose();
		if (ctrlUnit79ItemProvider != null) ctrlUnit79ItemProvider.dispose();
		if (ctrlUnit80ItemProvider != null) ctrlUnit80ItemProvider.dispose();
		if (ctrlUnit81ItemProvider != null) ctrlUnit81ItemProvider.dispose();
		if (ctrlUnit82ItemProvider != null) ctrlUnit82ItemProvider.dispose();
		if (ctrlUnit83ItemProvider != null) ctrlUnit83ItemProvider.dispose();
		if (ctrlUnit84ItemProvider != null) ctrlUnit84ItemProvider.dispose();
		if (ctrlUnit85ItemProvider != null) ctrlUnit85ItemProvider.dispose();
		if (ctrlUnit86ItemProvider != null) ctrlUnit86ItemProvider.dispose();
		if (ctrlUnit87ItemProvider != null) ctrlUnit87ItemProvider.dispose();
		if (ctrlUnit88ItemProvider != null) ctrlUnit88ItemProvider.dispose();
		if (ctrlUnit89ItemProvider != null) ctrlUnit89ItemProvider.dispose();
		if (ctrlUnit90ItemProvider != null) ctrlUnit90ItemProvider.dispose();
		if (ctrlUnit91ItemProvider != null) ctrlUnit91ItemProvider.dispose();
		if (ctrlUnit92ItemProvider != null) ctrlUnit92ItemProvider.dispose();
		if (ctrlUnit93ItemProvider != null) ctrlUnit93ItemProvider.dispose();
		if (ctrlUnit94ItemProvider != null) ctrlUnit94ItemProvider.dispose();
		if (ctrlUnit95ItemProvider != null) ctrlUnit95ItemProvider.dispose();
		if (ctrlUnit96ItemProvider != null) ctrlUnit96ItemProvider.dispose();
		if (ctrlUnit97ItemProvider != null) ctrlUnit97ItemProvider.dispose();
		if (ctrlUnit98ItemProvider != null) ctrlUnit98ItemProvider.dispose();
		if (ctrlUnit99ItemProvider != null) ctrlUnit99ItemProvider.dispose();
		if (ctrlUnit100ItemProvider != null) ctrlUnit100ItemProvider.dispose();
		if (ctrlUnit101ItemProvider != null) ctrlUnit101ItemProvider.dispose();
		if (ctrlUnit102ItemProvider != null) ctrlUnit102ItemProvider.dispose();
		if (ctrlUnit103ItemProvider != null) ctrlUnit103ItemProvider.dispose();
		if (ctrlUnit104ItemProvider != null) ctrlUnit104ItemProvider.dispose();
		if (ctrlUnit105ItemProvider != null) ctrlUnit105ItemProvider.dispose();
		if (ctrlUnit106ItemProvider != null) ctrlUnit106ItemProvider.dispose();
		if (ctrlUnit107ItemProvider != null) ctrlUnit107ItemProvider.dispose();
		if (ctrlUnit108ItemProvider != null) ctrlUnit108ItemProvider.dispose();
		if (ctrlUnit109ItemProvider != null) ctrlUnit109ItemProvider.dispose();
		if (ctrlUnit110ItemProvider != null) ctrlUnit110ItemProvider.dispose();
		if (ctrlUnit111ItemProvider != null) ctrlUnit111ItemProvider.dispose();
		if (ctrlUnit112ItemProvider != null) ctrlUnit112ItemProvider.dispose();
		if (ctrlUnit113ItemProvider != null) ctrlUnit113ItemProvider.dispose();
		if (ctrlUnit114ItemProvider != null) ctrlUnit114ItemProvider.dispose();
		if (ctrlUnit115ItemProvider != null) ctrlUnit115ItemProvider.dispose();
		if (ctrlUnit116ItemProvider != null) ctrlUnit116ItemProvider.dispose();
		if (ctrlUnit117ItemProvider != null) ctrlUnit117ItemProvider.dispose();
		if (ctrlUnit118ItemProvider != null) ctrlUnit118ItemProvider.dispose();
		if (ctrlUnit119ItemProvider != null) ctrlUnit119ItemProvider.dispose();
		if (ctrlUnit120ItemProvider != null) ctrlUnit120ItemProvider.dispose();
		if (ctrlUnit121ItemProvider != null) ctrlUnit121ItemProvider.dispose();
		if (ctrlUnit122ItemProvider != null) ctrlUnit122ItemProvider.dispose();
		if (ctrlUnit123ItemProvider != null) ctrlUnit123ItemProvider.dispose();
		if (ctrlUnit124ItemProvider != null) ctrlUnit124ItemProvider.dispose();
		if (ctrlUnit125ItemProvider != null) ctrlUnit125ItemProvider.dispose();
		if (ctrlUnit126ItemProvider != null) ctrlUnit126ItemProvider.dispose();
		if (ctrlUnit127ItemProvider != null) ctrlUnit127ItemProvider.dispose();
		if (ctrlUnit128ItemProvider != null) ctrlUnit128ItemProvider.dispose();
		if (ctrlUnit129ItemProvider != null) ctrlUnit129ItemProvider.dispose();
		if (ctrlUnit130ItemProvider != null) ctrlUnit130ItemProvider.dispose();
		if (ctrlUnit131ItemProvider != null) ctrlUnit131ItemProvider.dispose();
		if (ctrlUnit132ItemProvider != null) ctrlUnit132ItemProvider.dispose();
		if (ctrlUnit133ItemProvider != null) ctrlUnit133ItemProvider.dispose();
	}

}
