/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCErrorReaction;
import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit53}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit53Validator {
	boolean validate();

	boolean validateInput__iMachineStatusIndicator(WTCInput value);
	boolean validateInput__iStopConditionIndicator(WTCInput value);
	boolean validateInput__iManualByPass(WTCInput value);
	boolean validateInput__iMotorizing(WTCInput value);
	boolean validateInput__iFlagIntoWind(WTCInput value);
	boolean validateInput__iProtectionCondition(WTCInput value);
	boolean validateInput__iEmergencyCondition(WTCInput value);
	boolean validateInput__iDeenergizeCondition(WTCInput value);
	boolean validateOutput__oAutoStopCommand(WTCOutput value);
	boolean validateFault__fRunFault(WTCFault value);
	boolean validateTimer__tStartDelay(WTCTimer value);
	boolean validateTimer__tCheckRunFault(WTCTimer value);
	boolean validateErrorReaction__erMotorizing(WTCErrorReaction value);
}
