/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCFault;
import WTSpec.WTCInput;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit29}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit29Validator {
	boolean validate();

	boolean validateInput__iDigitalInput(WTCInput value);
	boolean validateInput__iDontCheckInput(WTCInput value);
	boolean validateFault__fFault(WTCFault value);
	boolean validateBhvParam__bpResetMode(String value);
}
