/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCParam;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit38}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit38Validator {
	boolean validate();

	boolean validateInput__iInput(WTCInput value);
	boolean validateInput__iDontCheckInput(WTCInput value);
	boolean validateParameter__pDelay(WTCParam value);
	boolean validateFault__fFault(WTCFault value);
	boolean validateTimer__tDelay(WTCTimer value);
	boolean validateBhvParam__bpLogicType(String value);
}
