/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit88}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit88Validator {
	boolean validate();

	boolean validateInput__iPthResetCommand(WTCInput value);
	boolean validateInput__iPthResetOrder(WTCInput value);
	boolean validateOutput__oPthResetCommand(WTCOutput value);
	boolean validateOutput__oPthResetOrder(WTCOutput value);
	boolean validateOutput__oPthReset(WTCOutput value);
	boolean validateTimer__tResetTimer(WTCTimer value);
	boolean validateTimer__tTimeBetweenResets(WTCTimer value);
}
