/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit42}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit42Validator {
	boolean validate();

	boolean validateInput__iInput(WTCInput value);
	boolean validateInput__iDontCheckInput(WTCInput value);
	boolean validateOutput__oActive(WTCOutput value);
	boolean validateOutput__oPulsing(WTCOutput value);
	boolean validateTimer__tDelay(WTCTimer value);
	boolean validateTimer__tActive(WTCTimer value);
}
