/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit60}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit60Validator {
	boolean validate();

	boolean validateInput__iDisconnect(WTCInput value);
	boolean validateInput__iStopCommand(WTCInput value);
	boolean validateInput__iPitchBraked(WTCInput value);
	boolean validateInput__iInverterRpm(WTCInput value);
	boolean validateInput__iReadyForOn(WTCInput value);
	boolean validateInput__iReadyForRun(WTCInput value);
	boolean validateInput__iReadyForRef(WTCInput value);
	boolean validateInput__iResetOrder(WTCInput value);
	boolean validateInput__iForceInvOff(WTCInput value);
	boolean validateInput__iSafetyInput(WTCInput value);
	boolean validateOutput__oInverterRun(WTCOutput value);
	boolean validateOutput__oInverterToOn(WTCOutput value);
	boolean validateParameter__pInverterConnSpeed(WTCParam value);
	boolean validateParameter__pInverterConnSpeedHysteresis(WTCParam value);
	boolean validateFault__fReconnectWarning(WTCFault value);
	boolean validateFault__fReadyRefWarning(WTCFault value);
	boolean validateTimer__tConnection(WTCTimer value);
	boolean validateTimer__tRunningDelay(WTCTimer value);
}
