/**
 * generated by Xtext 2.11.0
 */
package org.mondo.collaboration.policy.rules;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rule Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.mondo.collaboration.policy.rules.RuleConstraint#getAccess <em>Access</em>}</li>
 *   <li>{@link org.mondo.collaboration.policy.rules.RuleConstraint#getOperation <em>Operation</em>}</li>
 * </ul>
 *
 * @see org.mondo.collaboration.policy.rules.RulesPackage#getRuleConstraint()
 * @model
 * @generated
 */
public interface RuleConstraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Access</b></em>' attribute.
   * The literals are from the enumeration {@link org.mondo.collaboration.policy.rules.AccessibilityLevel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Access</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Access</em>' attribute.
   * @see org.mondo.collaboration.policy.rules.AccessibilityLevel
   * @see #setAccess(AccessibilityLevel)
   * @see org.mondo.collaboration.policy.rules.RulesPackage#getRuleConstraint_Access()
   * @model
   * @generated
   */
  AccessibilityLevel getAccess();

  /**
   * Sets the value of the '{@link org.mondo.collaboration.policy.rules.RuleConstraint#getAccess <em>Access</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Access</em>' attribute.
   * @see org.mondo.collaboration.policy.rules.AccessibilityLevel
   * @see #getAccess()
   * @generated
   */
  void setAccess(AccessibilityLevel value);

  /**
   * Returns the value of the '<em><b>Operation</b></em>' attribute.
   * The literals are from the enumeration {@link org.mondo.collaboration.policy.rules.OperationType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operation</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operation</em>' attribute.
   * @see org.mondo.collaboration.policy.rules.OperationType
   * @see #setOperation(OperationType)
   * @see org.mondo.collaboration.policy.rules.RulesPackage#getRuleConstraint_Operation()
   * @model
   * @generated
   */
  OperationType getOperation();

  /**
   * Sets the value of the '{@link org.mondo.collaboration.policy.rules.RuleConstraint#getOperation <em>Operation</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operation</em>' attribute.
   * @see org.mondo.collaboration.policy.rules.OperationType
   * @see #getOperation()
   * @generated
   */
  void setOperation(OperationType value);

} // RuleConstraint
