/**
 * generated by Xtext 2.11.0
 */
package org.mondo.collaboration.policy.rules;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>User</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.mondo.collaboration.policy.rules.RulesPackage#getUser()
 * @model
 * @generated
 */
public interface User extends Role
{
} // User
