/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit30}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit30Validator {
	boolean validate();

	boolean validateInput__iDigitalInput(WTCInput value);
	boolean validateInput__iOffOrder(WTCInput value);
}
