/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit82}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit82Validator {
	boolean validate();

	boolean validateInput__iVarInput(WTCInput value);
	boolean validateInput__iWriteTwistAngleRequest(WTCInput value);
	boolean validateInput__iNewTwistAngleValue(WTCInput value);
	boolean validateOutput__oVarOutput(WTCOutput value);
	boolean validateParameter__pMinDifferenceToConsider(WTCParam value);
	boolean validateTimer__tSyncDelay(WTCTimer value);
}
