/*
 * generated by Xtext
 */
package mondo.collab.security.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import mondo.collab.security.xtext.services.SecurityAccessGrammarAccess;

public class SecurityAccessParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SecurityAccessGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected mondo.collab.security.xtext.parser.antlr.internal.InternalSecurityAccessParser createParser(XtextTokenStream stream) {
		return new mondo.collab.security.xtext.parser.antlr.internal.InternalSecurityAccessParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AccessControlModel";
	}
	
	public SecurityAccessGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SecurityAccessGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
