/*
 * generated by Xtext
 */
package org.mondo.collaboration.security.macl.xtext.rule.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MACLRuleUiModule extends org.mondo.collaboration.security.macl.xtext.rule.ui.AbstractMACLRuleUiModule {
	public MACLRuleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
