/**
 * generated by Xtext
 */
package hu.bme.mit.ftsrg.mondo.accesscontrol.policydsl.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
@SuppressWarnings("all")
public class PolicyOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
