/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCErrorReaction;
import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit49}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit49Validator {
	boolean validate();

	boolean validateInput__iInput1(WTCInput value);
	boolean validateInput__iInput2(WTCInput value);
	boolean validateInput__iInput3(WTCInput value);
	boolean validateInput__iInput4(WTCInput value);
	boolean validateOutput__oOutputFan1(WTCOutput value);
	boolean validateOutput__oOutputFan2(WTCOutput value);
	boolean validateParameter__pParam1(WTCParam value);
	boolean validateParameter__pParam2(WTCParam value);
	boolean validateParameter__pParam3(WTCParam value);
	boolean validateParameter__pParam4(WTCParam value);
	boolean validateFault__fFault1(WTCFault value);
	boolean validateTimer__tTimer1(WTCTimer value);
	boolean validateErrorReaction__eReaction1(WTCErrorReaction value);
	boolean validateErrorReaction__eReaction2(WTCErrorReaction value);
	boolean validateGuard__gGuardErrors(String value);
	boolean validateGuard__gGuardNoErrors(String value);
	boolean validateGuard__gGuardOffToHi(String value);
	boolean validateGuard__gGuardHiToOff(String value);
	boolean validateGuard__gGuardOffToLow(String value);
	boolean validateGuard__gGuardLowToOff(String value);
	boolean validateGuard__gGuardLowToHi(String value);
	boolean validateGuard__gGuardHiToLow(String value);
}
