/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit26}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit26Validator {
	boolean validate();

	boolean validateInput__iCounter(WTCInput value);
	boolean validateInput__iActivator(WTCInput value);
	boolean validateOutput__oCounter(WTCOutput value);
	boolean validateOutput__oLimitReached(WTCOutput value);
	boolean validateParameter__pLimit(WTCParam value);
}
