/*
 * generated by Xtext
 */
package hu.bme.mit.ftsrg.mondo.accesscontrol.policydsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PolicyUiModule extends hu.bme.mit.ftsrg.mondo.accesscontrol.policydsl.ui.AbstractPolicyUiModule {
	public PolicyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
