/*
 * generated by Xtext
 */
package mondo.collab.security.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import mondo.collab.security.xtext.ui.internal.SecurityAccessActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SecurityAccessExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SecurityAccessActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SecurityAccessActivator.getInstance().getInjector(SecurityAccessActivator.MONDO_COLLAB_SECURITY_XTEXT_SECURITYACCESS);
	}
	
}
