#!/bin/bash

# Post-commit script is responsible for execute the "get" method of our lens when commit occurs on the gold repository.
# This hook has to be placed into the hooks directory of the gold repository.
# For the configuration, set the following variables:

URL='http://127.0.0.1' 				         #URL of the SVN repository provider (not ssh)
TEMP='/home/vialpando/tempsvn'			   #Temporary directory, where the script has enough permisson to create and copy files
FRONT_LIST="front1:alice" #front2:bob"		 #List of the front repositories - FRONT_LIST="repo1:userA repo2:userB repo3:userC ... repoN:userX"
LENS_SCRIPT='/home/vialpando/Eclipse/Mondo/lens/run.sh' #Lens script location. This script executes the lens.

JAVA_HOME="/usr/lib/jvm/java-8-oracle"
export PATH=$PATH:$JAVA_HOME

EXTENSION="wtspec4m"                  # We execute the lens on each file with the given extension

ADMIN_USER="admin"                    # Username of a user that has read and write permissions on all front repositories and on the gold repository
ADMIN_PWD="admin"                     # Password of a user that has read and write permissions on all front repositories and on the gold repository

GOLD_REPOS="$1"
REV="$2"
TXN="$3"

GOLD_REPOS_URL="$URL/$GOLD_REPOS@$REV"

set -e

TEMP_GOLD="$TEMP/tempGold$GOLD_REPOS"
TEMP_FRONTS="$TEMP/tempFront/Additional"

rm -rf $TEMP_FRONTS

if [ ! -d $TEMP_GOLD ]; then
  svn checkout "$GOLD_REPOS_URL" "$TEMP_GOLD" --username $ADMIN_USER --password $ADMIN_PWD --quiet --non-interactive
  echo "gold checkout ..... ok" 1>&2
fi

FILE_LIST="$(find $TEMP_GOLD -type f -name \*.$EXTENSION)"

for entry in $FRONT_LIST; do
  oldIFS=$IFS
  IFS=':'
  set x $entry
  FRONT_REPOS="$2"
  FRONT_USER="$3"
  current="$TEMP_FRONTS/$2"

  svn checkout "$URL/svn/$2" "$TEMP_FRONTS/$2" --username $ADMIN_USER --password $ADMIN_PWD --quiet --non-interactive
  echo "front checkout .... ok ($2)" 1>&2

  IFS="
"
  for gold in $FILE_LIST; do
    front=${gold/$TEMP_GOLD/$current}
    echo "asd $front" 1>&2
    echo "execute lens ... ok ($gold)" 1>&2
    $LENS_SCRIPT $FRONT_USER $gold $front '-performGet' $TEMP
    echo "lens finished .. ok ($gold)" 1>&2
  done

  IFS="$oldIFS"

  MSG=$(svnlook log -t $TXN $REPOS)

  cd $current

  svn add --force * --auto-props --parents --depth infinity -q
  echo "add files to svn ... ok" 1>&2

  echo "$MSG" 1>"svn-commit.tmp"
  svn commit -F svn-commit.tmp

done

rm -rf $TEMP_FRONTS/*
rm -rf $TEMP_GOLD/*
echo "final clear ........ ok" 1>&2
exit 0
