#!/bin/sh

# This script is responsible for executing a put back method of the lens.
#  * First, it checks out the front and gold repositories to the $USER folder.
#  * Second, it executes the put back of the lens (currently, a simple copy command will be executed)
#  * Third, it clears the $USER folder. 
#
# Setting:
#  * $URL          - provides the url of the svn repositories
#  * $MASTER_REPOS - provides the url of the golden repository
#  * $USER         - provides a directory, where the script has enough permission to create temporary files and folders

# Hook argument provided by SVN
REPOS="$1"
REV="$2"
TXN_NAME="$3"

# Custom variables. You have to modify these ones.
URL='http://localhost'
MASTER_REPOS="$URL/svn/mondo-testrepo/"
CLIENT_REPOS="$URL$REPOS@$REV"
USER='/home/vialpando/tempsvn'

set -e

echo $MASTER_REPOS 1>&2
echo $CLIENT_REPOS 1>&2

rm -rf $USER/*
echo "initial clear ...... ok" 1>&2

TEMP_ORIGIN="$USER/tempOrigin"
TEMP_CLIENT="$USER/tempClient"

svn checkout $MASTER_REPOS $TEMP_ORIGIN -q
echo "origin checkout .... ok" 1>&2

svn checkout $CLIENT_REPOS $TEMP_CLIENT -q
echo "client checkout .... ok" 1>&2

cp -a $TEMP_CLIENT/* $TEMP_ORIGIN
echo "copy content ....... ok" 1>&2

cd $TEMP_CLIENT
MSG=$(svn log -r COMMITTED)

cd $TEMP_ORIGIN

svn add --force * --auto-props --parents --depth infinity -q
echo "add files to svn ... ok" 1>&2

echo "$MSG" 1>"svn-commit.tmp"
svn commit -F svn-commit.tmp
echo "commit files ....... ok" 1>&2

rm -rf $USER/*
echo "final clear ........ ok" 1>&2
exit 0


