/*
 * generated by Xtext 2.11.0
 */
package org.mondo.collaboration.policy.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RulesAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/mondo/collaboration/policy/parser/antlr/internal/InternalRules.tokens");
	}
}
