/*
 * generated by Xtext
 */
package org.mondo.collaboration.security.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SecurityAccessUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.mondo.collaboration.security.xtext.ui.internal.SecurityAccessActivator.getInstance().getInjector("org.mondo.collaboration.security.xtext.SecurityAccess");
	}
	
}
