/*
 * generated by Xtext
 */
package mondo.collab.security.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SecurityAccessUiModule extends mondo.collab.security.xtext.ui.AbstractSecurityAccessUiModule {
	public SecurityAccessUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
