/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCErrorReaction;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit84}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit84Validator {
	boolean validate();

	boolean validateInput__iAngleGH1(WTCInput value);
	boolean validateInput__iAngleGH2(WTCInput value);
	boolean validateInput__iAngleGH3(WTCInput value);
	boolean validateInput__iStopCommand(WTCInput value);
	boolean validateInput__iFlBrakes(WTCInput value);
	boolean validateOutput__oAngleReference1(WTCOutput value);
	boolean validateOutput__oAngleReference2(WTCOutput value);
	boolean validateOutput__oAngleReference3(WTCOutput value);
	boolean validateOutput__oSpeedReference(WTCOutput value);
	boolean validateOutput__oAccelerationReference(WTCOutput value);
	boolean validateParameter__pPitchBrakeAngle(WTCParam value);
	boolean validateParameter__pPitchStdSpeed(WTCParam value);
	boolean validateParameter__pPitchStdAcceleration(WTCParam value);
	boolean validateParameter__pPitchRegulationSpeed(WTCParam value);
	boolean validateParameter__pPitchRegulationAcceleration(WTCParam value);
	boolean validateErrorReaction__erEmergency(WTCErrorReaction value);
}
