/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit66}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit66Validator {
	boolean validate();

	boolean validateInput__iMaintenancePreventiveButton(WTCInput value);
	boolean validateInput__iMaintenanceCorrectiveButton(WTCInput value);
	boolean validateInput__iDontCheckInput(WTCInput value);
	boolean validateOutput__oMaintenanceStatus(WTCOutput value);
	boolean validateFault__fMaintenancePreventive(WTCFault value);
	boolean validateFault__fMaintenanceCorrective(WTCFault value);
}
