/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit23}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit23Validator {
	boolean validate();

	boolean validateInput__iWindSpeed(WTCInput value);
	boolean validateInput__iInverterPower(WTCInput value);
	boolean validateOutput__oRelationError(WTCOutput value);
	boolean validateParameter__pWindSpeedLimit(WTCParam value);
	boolean validateParameter__pInverterPowerLimit(WTCParam value);
	boolean validateTimer__tWindMinimumTime(WTCTimer value);
	boolean validateTimer__tPowerAndWindMinimumTime(WTCTimer value);
}
