/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCInput;
import WTSpec.WTCOutput;
import WTSpec.WTCParam;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit114}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit114Validator {
	boolean validate();

	boolean validateInput__iWindDirectionRaw(WTCInput value);
	boolean validateInput__iNacelleDirection(WTCInput value);
	boolean validateOutput__oWindDirection(WTCOutput value);
	boolean validateOutput__oWindDirectionAverage(WTCOutput value);
	boolean validateOutput__oWindDirectionDispAbsolute(WTCOutput value);
	boolean validateOutput__oWindDirectionDispRelative(WTCOutput value);
	boolean validateParameter__pVaneOffset(WTCParam value);
}
