/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.Subsystem;
import WTSpec.wtc;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link WTSpec.Subsystem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubsystemValidator {
	boolean validate();

	boolean validateSysId(String value);
	boolean validateDescription(String value);
	boolean validateItsWTCs(EList<wtc> value);
	boolean validateItsSubsystems(EList<Subsystem> value);
}
