#!/bin/sh
#DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
DIR=/mondo
. $DIR/config.properties

# Pre-commit script is responsible for execute the "put back" method of our lens when a client commits changes to a front repository.
# This hook has to be placed into the hooks directory of every front repository.
# For the configuration, set the following variables:

GOLD_REPOS_URL="$URL/$SVN_PATH_URL/$GOLD_REPO_NAME"		  #URL of the gold repository
export PATH=$PATH:$JAVA_HOME

function replace {
    echo "${1/$2/$3}"
}

CURRENT_FRONT_REPOS="$1"
CURRENT_FRONT_REPOS_URL="$URL$CURRENT_FRONT_REPOS"
TXN="$2"

TEMP_GOLD="$TEMP/tempGoldPre/$GOLD_REPO_NAME"
TEMP_FRONT="$TEMP/tempFront/Current$CURRENT_FRONT_REPOS"
FRONT_USER=$(svnlook author -t $TXN $CURRENT_FRONT_REPOS)

CURRENT_FRONT_REPOS_NAME=$(replace $CURRENT_FRONT_REPOS "/$SVN_PATH_URL" "")

LOG="$DIR/pre-commit.log"

timestamp() {
  date +"%Y-%m-%d_%H-%M-%S"
}

log() {
  echo "$(timestamp) $1" 1>>$LOG
}

log "-------------------------------------------------------"
log "Executing Pre-commit"
log "Parameters"
log "      TXN $TXN"
log "      URL $URL"
log "      GOLD_REPOS $GOLD_REPO_NAME"
log "      GOLD_REPOS_URL $GOLD_REPOS_URL"
log "      CURRENT_REPOS $CURRENT_FRONT_REPOS"
log "      CURRENT_REPOS_URL $CURRENT_FRONT_REPOS_URL"
log "      TEMP $TEMP"
log "      LENS_SCRIPT $LENS_SCRIPT"
log "      JAVA_HOME $JAVA_HOME"
log "      MODEL_EXTENSIONS $MODEL_EXTENSIONS"
log "      ADMIN_USER $ADMIN_USER"
log "      ADMIN_PWD $ADMIN_PWD"
log "      TEMP_GOLD $TEMP_GOLD"
log "      TEMP_FRONT $TEMP_FRONT"
log "      FRONT_USER $FRONT_USER"

set -e

if [ "$FRONT_USER" = "$ADMIN_USER" ]; then
  log "Admin was the committer. Nothing to do right now"
  log "-------------------------------------------------------"
  exit 0
fi

log "Clear temp folder - $TEMP"
rm -rf $TEMP/*

log "Checkout gold - from $GOLD_REPOS_URL to $TEMP_GOLD"
svn checkout $GOLD_REPOS_URL $TEMP_GOLD -q --username $ADMIN_USER --password $ADMIN_PWD --quiet --non-interactive

log "Get change list"
changes=$(svnlook changed -t $TXN $CURRENT_FRONT_REPOS)

log "Get commit message"
MSG=$(svnlook log -t $TXN $CURRENT_FRONT_REPOS)

mkdir -p $TEMP_FRONT

obfuscatorSeed="seed_$CURRENT_FRONT_REPOS_NAME"
obfuscatorSalt="salt_$CURRENT_FRONT_REPOS_NAME"
obfuscatorPrefix="mondo"

log "Start iterating over the changes"
counter=0
for line in $changes; do
   val=$(($counter % 2))
   if [ $val = 0 ]
   then
       nextType=$line
   fi
   if [ $val = 1 ]
   then
   	nextChange=$line
    log "     -> Change: $nextType $nextChange"
  	if [ $nextType = "A" ] || [ $nextType = "U" ] || [ $nextType = "UU" ]
  	then
  	   case $nextChange in
       		*/)
          log "     -> Action: Create Dir $TEMP_GOLD/$nextChange"
          mkdir -p "$TEMP_GOLD/$nextChange"
          ;;
       		*)
          log "     -> Action: Copy Content $TEMP_FRONT/$nextChange"
          DIR="$TEMP_FRONT/$nextChange"
          BASEDIR=$(dirname "${DIR}")
          if [ ! -d $BASEDIR ]
          then
            mkdir -p $BASEDIR
          fi
          svnlook cat -t $TXN $CURRENT_FRONT_REPOS $nextChange > "$TEMP_FRONT/$nextChange"
          if [[ $nextChange =~ .${MODEL_EXTENSIONS}$ ]]
          then
            log "     -> Action: Execute lens $TEMP_FRONT/$nextChange"
            log "Obfuscator $obfuscatorSeed $obfuscatorSalt $obfuscatorPrefix"
            $LENS_SCRIPT $FRONT_USER $TEMP_GOLD/$nextChange $TEMP_FRONT/$nextChange -performPutback $TEMP $obfuscatorSalt $obfuscatorSeed $obfuscatorPrefix "$TEMP_GOLD/$ACCESS_CONTROL_RULES" "$TEMP_GOLD/$ACCESS_CONTROL_QUERIES"
          else
            log "     -> Action: Copy to gold $TEMP_FRONT/$nextChange"
            cp -rf $TEMP_FRONT/$nextChange $TEMP_GOLD/$nextChange
          fi
          ;;
  	   esac
    fi

  	if [ $nextType = "D" ]
  	then
      log "     -> Action: Delete $TEMP_GOLD/$nextChange"
      rm -rf "$TEMP_GOLD/$nextChange"
    fi
   fi
   counter=$((counter+1))
done

log "Step into the gold folder"
cd $TEMP_GOLD

log "Add changes to SVN"
svn add --force * --auto-props --parents --depth infinity -q

log "Store commit message"
echo "$MSG" 1>"svn-commit.tmp"

log "Commit changes to the gold"
svn commit -F svn-commit.tmp --username $ADMIN_USER --password $ADMIN_PWD --quiet --non-interactive

log "Remove temporary files"
rm -rf $TEMP/*

log "Pre-commit finished successfully"
exit 0
