/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCParam;
import WTSpec.WTCTimer;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit24}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit24Validator {
	boolean validate();

	boolean validateInput__iInverterReady(WTCInput value);
	boolean validateInput__iInverterPower(WTCInput value);
	boolean validateInput__iAlgorithmCommand(WTCInput value);
	boolean validateParameter__pPowerLimit(WTCParam value);
	boolean validateFault__fYawProblem(WTCFault value);
	boolean validateTimer__tDelayProblemNotify(WTCTimer value);
	boolean validateDecisionSequence__dsDecisionTree(String value);
}
