/**
 *
 * $Id$
 */
package WTSpec.validation;

import WTSpec.WTCFault;
import WTSpec.WTCInput;
import WTSpec.WTCOutput;

/**
 * A sample validator interface for {@link WTSpec.CtrlUnit79}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CtrlUnit79Validator {
	boolean validate();

	boolean validateInput__iOverPressureCmd(WTCInput value);
	boolean validateOutput__oYawBrakeHighPressureCmd(WTCOutput value);
	boolean validateFault__fYawBrakeBlock(WTCFault value);
	boolean validateFault__fYawBrakeLoose(WTCFault value);
	boolean validateFault__fYawBrakeActive(WTCFault value);
	boolean validateFault__fWarning(WTCFault value);
	boolean validateFault__fFault(WTCFault value);
	boolean validateDecisionSequence__dsCommands(String value);
}
